
var cnf=require('./config.js');var router=require('express').Router();router.post('/acceso/',function(req,res){var version=req.headers.version;if(version==='1.0.0')
return acceder(req,res);return res.status(320).send({m:MENSAJE_DEPRECATE});});const SQL_REGISTRAR_INGRESO="INSERT INTO "+_BD_+".movimiento (idCompania, idTarjeta, estado, idLugar, fechaHoraIngreso, tipo,metodo) VALUES (?, ?, 1, ?, now(), ?, ?)";const SQL_EXISTE_TARJETA="SELECT t.idTarjeta,t.tipoAcceso FROM "+_BD_+".tarjeta t WHERE t.tarjeta = ? ;";const SQL_EXISTE_ANTENA="SELECT e.ubicacion,e.codigo,e.acronimo,e.ip FROM "+_BD_+".equipo e WHERE e.acronimo = ?;";const SQL_EXISTE_LETRERO="SELECT e.acronimo,e.ip FROM "+_BD_+".equipo e WHERE e.codigo = ? and e.ip != ?;";const SQL_AUTORIZADO="SELECT tlh.idHorario,l.idCompania,ta.idAsignado,t.idTarjeta FROM "+_BD_+".tarjeta t"+" INNER JOIN "+_BD_+".tarjetaAsignacion ta on ta.idTarjeta=t.idTarjeta and ta.habilitado=1"+" INNER JOIN "+_BD_+".tarjetaLugarHorario tlh on tlh.idTarjeta=t.idTarjeta and tlh.eliminado=0 and tlh.idLugar=?"+" INNER JOIN "+_BD_+".lugar l on l.idLugar=tlh.idLugar "+" WHERE t.tarjeta = ? and (DATE_ADD(current_timestamp(), INTERVAL -5 HOUR) between tlh.fechaInicio and tlh.fechaFin);";const SQL_HORARIO=" SELECT * from "+_BD_+".horarioDetalle hd "+" where hd.idHorario=? and hd.dia = DAYOFWEEK(date(DATE_ADD(current_timestamp(), INTERVAL -5 HOUR))) "+" and (time(DATE_ADD(current_timestamp(), INTERVAL -5 HOUR)) between hd.desde and hd.hasta);"
function acceder(req,res){var idAntena=req.body.idAntena;var idTarjeta=req.body.idTarjeta;var idLugar=req.body.idLugar;var origen=req.body.origen;var metodo=req.body.metodo;if(!idAntena)
return res.status(400).send({error:1,param:'idAntena'});if(!idTarjeta)
return res.status(400).send({error:1,param:'idTarjeta'});if(!idLugar)
return res.status(400).send({error:1,param:'idLugar'});if(!metodo)
metodo=1;if(origen==2){metodo=4;}
console.log(idAntena);console.log(idTarjeta);console.log(idLugar);console.log(origen);console.log(metodo);console.log('---------------');cnf.ejecutarResSQL(SQL_EXISTE_ANTENA,[idAntena],function(antena){if(antena.length<=0)
return res.status(200).send({en:-1,m:'Antena no registrada',com:''});if(antena[0]['ubicacion']==1)
cnf.ejecutarResSQL(SQL_EXISTE_LETRERO,[antena[0]['codigo'],antena[0]['ip']],function(letrero){var existeLetrero=true;if(letrero.length<=0)
existeLetrero=false;cnf.ejecutarResSQL(SQL_EXISTE_TARJETA,[idTarjeta],function(tarjetas){if(tarjetas.length<=0)
if(existeLetrero)
return res.status(200).send({en:-1,m:'Tag no registrado',com:'$$'+letrero[0]['acronimo']+',MSG,1##',ip:letrero[0]['ip']});else
return res.status(200).send({en:-1,m:'Tag no registrado',com:'',ip:''});cnf.ejecutarResSQL(SQL_AUTORIZADO,[idLugar,idTarjeta],function(tarjetaLugar){if(tarjetaLugar.length<=0)
if(existeLetrero)
return res.status(200).send({en:-1,m:'Vehiculo no autorizado',com:'$$'+letrero[0]['acronimo']+',MSG,2##',ip:letrero[0]['ip']});else
return res.status(200).send({en:-1,m:'Vehiculo no autorizado',com:'',ip:''});cnf.ejecutarResSQL(SQL_HORARIO,[tarjetaLugar[0]['idHorario']],function(horarios){if(horarios.length<=0)
if(existeLetrero)
return res.status(200).send({en:-1,m:'Fuera de horario',com:'$$'+letrero[0]['acronimo']+',MSG,3##',ip:letrero[0]['ip']});else
return res.status(200).send({en:-1,m:'Fuera de horario',com:'',ip:''});cnf.ejecutarResSQL(SQL_BUSCAR_USUARIO,[tarjetaLugar[0]['idAsignado'],tarjetaLugar[0]['idTarjeta'],idLugar],function(usuarioComprobacion){if(usuarioComprobacion.length>0)
if(existeLetrero)
return res.status(200).send({en:-1,m:'Otro tag adentro',com:'$$'+letrero[0]['acronimo']+',MSG,3##',ip:letrero[0]['ip']});else
return res.status(200).send({en:-1,m:'Otro tag adentro',com:'',ip:''});var tipoAcceso=1;if(tarjetas[0]['tipoAcceso']==1){tipoAcceso=3;}
cnf.ejecutarResSQL(SQL_REGISTRAR_INGRESO,[tarjetaLugar[0]['idCompania'],tarjetas[0]['idTarjeta'],idLugar,tipoAcceso,metodo],function(session){if(session['affectedRows']>0){if(origen==2){console.log("enviando datos a parqueadero");global.EMIT.emit('en_datos',{en:1,idL:idLugar,com:'$$ABRIR'+idAntena+'##',ip:antena[0]['ip']});}
return res.status(200).send({en:1,m:'Acceso Correcto',com:'$$ABRIR'+idAntena+'##',ip:antena[0]['ip']});}
return res.status(200).send({en:-1,m:'error al ingreso',com:''});},res);},res);},res);},res);},res);},res);else
cnf.ejecutarResSQL(SQL_AUTORIZADO_SALIDA,[idLugar,idTarjeta],function(autorizacion){if(autorizacion.length<=0)
return res.status(200).send({en:-1,m:'salida no autorizada',com:''});cnf.ejecutarResSQL(SQL_ENCONTRAR_MOVIMIENTO,[idTarjeta,idLugar],function(movimiento){if(movimiento.length<=0){var tipoAcceso=1;if(autorizacion[0]['tipoAcceso']==1){tipoAcceso=3;}
cnf.ejecutarResSQL(SQL_REGISTRAR_SALIDA_SIN_INGRESO,[autorizacion[0]['idCompania'],autorizacion[0]['idTarjeta'],idLugar,tipoAcceso,metodo],function(session){if(session['affectedRows']>0){if(origen==2){metodo=4;console.log("enviando datos a parqueadero");global.EMIT.emit('en_datos',{en:1,idL:idLugar,antena:idAntena,com:'$$ABRIR'+idAntena+'##',ip:antena[0]['ip']});}
return res.status(200).send({en:1,com:'$$ABRIR'+idAntena+'##',ip:antena[0]['ip'],m:'salida sin ingreso'});}
return res.status(200).send({en:-1,m:'error en la salida sin ingreso',com:''});},res);}else
cnf.ejecutarResSQL(SQL_REGISTRAR_SALIDA,[movimiento[0]['idTarjeta'],idLugar],function(session){if(session['affectedRows']>0){if(origen==2){console.log("enviando datos a parqueadero");global.EMIT.emit('en_datos',{en:1,idL:idLugar,com:'$$ABRIR'+idAntena+'##',ip:antena[0]['ip']});}
return res.status(200).send({en:1,com:'$$ABRIR'+idAntena+'##',ip:antena[0]['ip'],m:'Cambio de estado'});}
return res.status(200).send({en:-1,m:'error en la salida',com:''});},res);},res);},res);},res);}
const SQL_ENCONTRAR_MOVIMIENTO="SELECT idMonimiento,m.idTarjeta FROM "+_BD_+".movimiento m "+" INNER JOIN "+_BD_+".tarjeta t on t.idTarjeta = m.idTarjeta "+" WHERE t.tarjeta=? AND m.idLugar=? AND m.estado=1 order by m.fechaHoraIngreso desc limit 1 ;";const SQL_REGISTRAR_SALIDA="UPDATE "+_BD_+".movimiento SET estado='2', fechaHoraSalida=now() WHERE idTarjeta=? and idLugar=? and estado=1";const SQL_BUSCAR_USUARIO="select idMonimiento as total from "+_BD_+".movimiento where idTarjeta in(select ta.idTarjeta from tarjetaAsignacion ta inner join usuario u on  u.idUsuario = ta.idAsignado where idAsignado=? and not idTarjeta=? and habilitado=1 and u.multimpleAcceso=0)  and estado =1 and idLugar=?;";const SQL_AUTORIZADO_SALIDA="SELECT t.tipoAcceso,tlh.idHorario,l.idCompania,ta.idAsignado,t.idTarjeta FROM "+_BD_+".tarjeta t"+" INNER JOIN "+_BD_+".tarjetaAsignacion ta on ta.idTarjeta=t.idTarjeta and ta.habilitado=1"+" INNER JOIN "+_BD_+".tarjetaLugarHorario tlh on tlh.idTarjeta=t.idTarjeta and tlh.eliminado=0 and tlh.idLugar=?"+" INNER JOIN "+_BD_+".lugar l on l.idLugar=tlh.idLugar "+" WHERE t.tarjeta = ?;";const SQL_REGISTRAR_SALIDA_SIN_INGRESO="INSERT INTO "+_BD_+".movimiento (idCompania, idTarjeta, estado, idLugar, fechaHoraSalida, tipo,metodo) VALUES (?, ?, 2, ?, now(), ?,?)";router.post('/tagbyplaca/',function(req,res){var version=req.headers.version;if(version==='1.0.0')
return listarTarjeta(req,res);return res.status(320).send({m:MENSAJE_DEPRECATE});});function listarTarjeta(req,res){var placa=req.body.placa;if(!placa)
return res.status(400).send({en:-1,param:'placa'});cnf.ejecutarResSQL(SQL_PLACA,[placa],function(tarjetas){if(tarjetas.length<=0)
return res.status(200).send({en:-1,m:'No Existen tarjetas asociadas a esta placa.'});return res.status(200).send({en:1,t:tarjetas[0]['tarjeta']});},res);}
const SQL_PLACA="SELECT tarjeta FROM kparkingutpl.tarjeta t  inner join tarjetaVehiculo tv on t.idTarjeta = tv.idTarjeta and tv.habilitado=1 inner join vehiculo v on v.idVehiculo=tv.idVehiculo  where t.eliminado=0 and v.placa=?;";module.exports=router;