global.ID_APLICATIVO_CLIPP = 1;
global.APLICATIVO_CLIPP = 'Clipp';

global.ID_APLICATIVO_PUNTUALL = 2;
global.APLICATIVO_PUNTUALL = 'Puntuall';

global.ID_APLICATIVO_CLIPP_TAXI = 27;
global.APLICATIVO_PUNTUALL = 'ClippTaxi';